import Head from 'next/head'
import styles from '../styles/Home.module.css'
import LetterRow from '../components/LetterRow'
import { useState } from 'react'

export default function Home() {
  const [guesses, setGuesses] = useState([])

  const handleRowChange = (letters, colours, index=0) => {
    const newGuesses = [...guesses]

    const row = letters.map((r,i) => {
      return {
        "letter": r,
        "color": colours[i] || "white"
      }
    })

    newGuesses[index] = row

    setGuesses(newGuesses)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to 5olve
        </h1>

        <div className="my-4">Type these letters in then click on the letters to change the colours</div>
        <LetterRow
          onChange={handleRowChange}
          rowIndex={0}
          startLetters={["A","R","O","S","E"]}
        />

        <div className="my-4">This is the next set of letters</div>
        <LetterRow
          onChange={handleRowChange}
          rowIndex={0}
          startLetters={["T","I","L","E","D"]}
        />

      </main>


    </div>
  )
}
