import Head from 'next/head'
import styles from '../styles/Home.module.css'
import LetterRow from '../components/LetterRow'
import { useEffect, useState } from 'react'
import { Entry } from './api/word'

async function getNextWord(req: Entry[][]): Promise<string> {
  const res = await fetch("/api/word", {method: "POST", body: JSON.stringify({words: req})})
  const json = await res.json();
  return json.word;
}

export default function Home() {
  const [guesses, setGuesses] = useState<Entry[][]>([]);
  const [nextLetters, setNextLetters] = useState<string>(null);
  const [loading, setLoading] = useState<boolean>(false);

  async function getWord(guesses: Entry[][]) {
    setLoading(true);
    const word = await getNextWord(guesses);
    setNextLetters(word);
    setLoading(false);
  }

  useEffect(() => {
    getWord([]);
  }, [])

  const handleRowChange = (letters: string[], colours) => {
    const row = letters.map((r,i) => {
      return {
        "letter": r,
        "color": colours[i] || "gray"
      }
    })

    setGuesses(g => [...g, row]);
    getWord([...guesses, row]);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to 5olve
        </h1>

        {guesses.map(guess => (
          <LetterRow
            key={guess.map(g => g.letter).join()}
            initialLetters={guess.map(g => g.letter)}
            initialColors={guess.map(g => g.color)}
          />
        ))}

        <div className="my-4">Type these letters in then click on the letters to change the colours</div>
        <div className="my-4">This is the next set of letters</div>
        {loading || nextLetters === null ? (
          <div>loading</div>
        ) : (
          <LetterRow
            onChange={handleRowChange}
            initialLetters={Array.from(nextLetters)}
            initialColors={[...Array(5)].map(() => "gray")}
          />
        )}
      </main>


    </div>
  )
}
